spring:
  application:
    name: frontend
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
logging:
  level:
    root: INFO
    dtfb: TRACE