spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetchRegistry: true