spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: bot
          uri: lb://bot
          predicates:
            - Path=/api/**
        - id: frontend
          uri: lb://frontend
          predicates:
            - Path=/forum/**
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetchRegistry: true