spring:
  application:
    name: bot
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
logging:
  level:
    root: INFO
    dtfb: TRACE